apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: duyo
resources:

  - database/db-configmap.yaml
  - database/db-secrets.yaml
  - database/pvc.yaml
  - database/db-deploy.yaml
  - database/db-svc.yaml

  - app/redmine-configmap.yaml
  - app/redmine-secrets.yaml
  - app/redmine-deploy.yaml
  - app/redmine-ing.yaml
  - app/redmine-svc.yaml