apiVersion: v1
kind: Service
metadata:
  name: redmine-db-svc
spec:
  selector:
    app: redmine-db
  ports:
    - name: '80'
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP